### PR TITLE
Vendor `buildbot` from the `nixpkgs` input (`nixpkgs-unstable-small`)

### PR DESCRIPTION
**Pull request by MagicRB**
This PR vendors `buildbot` by adding an overlay that pulls it from our checkout of `nixpkgs-unstable-small`, this assumes that consumers of this flake will not make said input follow their own checkout of `nixpkgs`. It might be better to add another input just for buildbot, but that also inflates the flake unnecessarily.

~TODO: add toggle for the overlay and error message if `buildbot` is older than 4.~

### CODE REVIEW

**Comment by MagicRB** [comment]
Ready, tested to work on my server running nixos 24.05 from a few weeks ago. (unfortunately it is really hard to see what I changed because a large reformat had to be done)

**Comment by zimbatm** [comment]
I think the package recipe could be moved to this repo as well.

**Comment by MagicRB** [comment]
I think that can be a separate issue/PR. and combined with the vendored module you mentioned in #216

**Comment by zowoq** [comment]
React is the default in buildbot 4 so can change/remove these now that this repo only targets that version.
```diff
diff --git a/buildbot_nix/__init__.py b/buildbot_nix/__init__.py
index d5d1d41..021768b 100644
--- a/buildbot_nix/__init__.py
+++ b/buildbot_nix/__init__.py
@@ -902,7 +902,6 @@ class NixConfigurator(ConfiguratorBase):
         config["secretsProviders"].append(systemd_secrets)
 
         config["www"].setdefault("plugins", {})
-        config["www"]["plugins"].update(dict(base_react={}))
 
         config["www"].setdefault("change_hook_dialects", {})
         for backend in backends.values():
diff --git a/nix/master.nix b/nix/master.nix
index 4085053..566a058 100644
--- a/nix/master.nix
+++ b/nix/master.nix
@@ -415,7 +415,7 @@ in
           ps.treq
           ps.psycopg2
           (ps.toPythonModule pkgs.buildbot-worker)
-          pkgs.buildbot-plugins.www-react
+          pkgs.buildbot-plugins.www
           (pkgs.python3.pkgs.callPackage ../default.nix { })
           (pkgs.python3.pkgs.callPackage ./buildbot-gitea.nix { buildbot = cfg.package; })
         ];

```

**Comment by Mic92** [comment]
This one is now obsolete.

**Pull request closed without merging**
