### PR TITLE
Defer webhook creation to project reload

### PR DESCRIPTION
**Pull request by MagicRB**

### CODE REVIEW

**Comment by MagicRB** [comment]
Do *NOT* test now, will end up creating a webhook for every single repo it has access to :/

**Comment by MagicRB** [comment]
Will keep on my instance for a while and check over once more, this is a way more intrusive change than I was hoping for.

**Comment by Mic92** [comment]
@mergify unqueue

**Comment by Mic92** [comment]
@mergify rebase

**Comment by Mic92** [comment]
I actually just wanted to rebase this, not merge it.

**Comment by MagicRB** [comment]
Did we merge this by another PR? The code from this seems to be in `master`

**Comment by zowoq** [comment]
> Did we merge this by another PR? The code from this seems to be in `master`

Looks like https://github.com/nix-community/buildbot-nix/pull/203?

**Comment by MagicRB** [comment]
Oh yeah, you're right, i even wrote that code :sweat_smile: I really have the memory of a goldfish (might be an insult to goldfish all over the world)

**Pull request closed without merging**
