### PR TITLE
remove automatic retry

### PR DESCRIPTION
**Pull request by zowoq**
Automatic retry is nice when the build is cheap, not so much if it is a multi-hour build.

I don't see a problem with removing this now that now that everyone has restart permissions.

### CODE REVIEW

**Comment by Mic92** [comment]
nix-community is a bit of a special case because we have many users there, however for many smaller instances the default should be ok. I made this now configurable: https://github.com/nix-community/buildbot-nix/pull/210

**Comment by zowoq** [comment]
Thanks.

**Comment by zowoq** [comment]
How do I set zero retries?

```
      buildRetries = lib.mkOption {
        type = lib.types.ints.positive;
        default = 1;
        description = "Number of times a build is retried";
      };
```

**Comment by Mic92** [comment]
Does ints.positive doesn't allow 0? we can also change it to int otherwise.

**Comment by zowoq** [comment]
```
error: A definition for option `services.buildbot-nix.master.buildRetries' is not of type `positive integer, meaning >0'
```

**Comment by Mic92** [comment]
https://github.com/nix-community/buildbot-nix/pull/211

**Comment by zowoq** [comment]
https://buildbot.nix-community.org/#/builders/37/builds/70

Just noticed this, got caught in a loop somehow?  Looked like it was happening in a couple of different repos.

I've reverted it for now. https://github.com/nix-community/infra/pull/1365

**Pull request closed without merging**
