### PR TITLE
[total untested] async syntax

### PR DESCRIPTION
**Pull request by Mic92**
according to twisted documentation, this should work?

### CODE REVIEW

**Comment by MagicRB** [comment]
If this worked, it would be sooo good

**Comment by MagicRB** [comment]
@Mic92 you missed some, 
https://github.com/nix-community/buildbot-nix/blob/main/buildbot_nix/__init__.py#L289
https://github.com/nix-community/buildbot-nix/blob/main/buildbot_nix/nix_status_generator.py#L61

**Comment by zowoq** [comment]
Looks like there is something wrong with this, seems the scheduler is only allowing one build at a time?

**Comment by Mic92** [comment]
Indeed. I will run a git bisect.

**Comment by Mic92** [comment]
@zowoq I think I found the issue: https://github.com/nix-community/buildbot-nix/pull/317
I think the old code was incorrect and async/await checks just uncovered it.

**Pull request merged**
