### PR TITLE
Fix typo, secretKeyFile is a path not a string

### PR DESCRIPTION
**Pull request by Erethon**
Minor documentation fix after the recent GitHub App changes

### CODE REVIEW

**Comment by Mic92** [comment]
Does it not accept strings at all? We actually want that to not import secrets into the nix store.

**Comment by MagicRB** [comment]
It ahould not be a path, if anything we should deny that in the module.

**Comment by Mic92** [comment]
What does your string looks like? This is what I have set:

```
nix-repl> nixosConfigurations.eve.config.services.buildbot-nix.master.github.authType.app.secretKeyFile
"/run/secrets/buildbot-github-app-secret-key"
```

It's by the way the same as for all other secret option. The string needs to contain an absolute path.

**Comment by Erethon** [comment]
> What does your string looks like? This is what I have set:
> 
> ```
> nix-repl> nixosConfigurations.eve.config.services.buildbot-nix.master.github.authType.app.secretKeyFile
> "/run/secrets/buildbot-github-app-secret-key"
> ```
> 
> It's by the way the same as for all other secret option. The string needs to contain an absolute path.

I didn't realize the string had to be an absolute path and I was using a relative one. Ehen I saw the code and error message it made sense to me to have this as a path and not a string. Closing this as invalid then, thank you!

PS. Sorry for the late reply, I was afk for a while.

**Pull request closed without merging**
