### PR TITLE
fix cachix

### PR DESCRIPTION
**Pull request by zowoq**
I think this is might be fixed but I'll test it in a couple of hours to make sure.

```
❯ nix eval .#nixosConfigurations.example-cachix-master-worker-combined-x86_64-linux.config.systemd.services.buildbot-master.serviceConfig.LoadCredential
[ "buildbot-nix-workers:/nix/store/zjhcahczn8b64kw90bbxzhlvw5smm0vi-workers.json" "github-webhook-secret:/nix/store/svaxdh1zss9jgs7365s601gxprg633jv-webhookSecret" "github-app-secret-key:/nix/store/z3yssjnmvpp3vfbyr7i7r8f3qfqgydc1-app-secret.key" "github-oauth-secret:/nix/store/jbvsw789q8g1a23cc9qvq5jhf14mf8v2-oauthSecret" ]
```
```
❯ nix eval .#nixosConfigurations.example-cachix-master-worker-combined-x86_64-linux.config.systemd.services.buildbot-master.serviceConfig.LoadCredential
[ "buildbot-nix-workers:/nix/store/zjhcahczn8b64kw90bbxzhlvw5smm0vi-workers.json" "github-webhook-secret:/nix/store/svaxdh1zss9jgs7365s601gxprg633jv-webhookSecret" "github-app-secret-key:/nix/store/z3yssjnmvpp3vfbyr7i7r8f3qfqgydc1-app-secret.key" "github-oauth-secret:/nix/store/jbvsw789q8g1a23cc9qvq5jhf14mf8v2-oauthSecret" "cachix-auth-token:/var/lib/secrets/cachix-token" ]
```

### CODE REVIEW

**Comment by Mic92** [comment]
ok. just merge when you tested it.

**Comment by zowoq** [comment]
```
builtins.AttributeError: 'NixConfigurator' object has no attribute 'post_build_steps'
```

**Comment by MagicRB** [comment]
@zowoq https://github.com/nix-community/buildbot-nix/blob/main/buildbot_nix/__init__.py#L944 that needs to be `self.config.post_build_steps`, it should make cachiz work, before I do such a big refactor I need to figure out better typing... This would have been caught by an actual type system.

**Comment by zowoq** [comment]
```
builtins.AttributeError: 'NixConfigurator' object has no attribute 'cachix'
```

**Comment by MagicRB** [comment]
Okay I'll get my laptop and pick this up, what code are you testing with?

**Comment by zowoq** [comment]
> Okay I'll get my laptop and pick this up, what code are you testing with?

Sorry, forgot to reply to this, I've pushed a change to the vm test that will check buildbot starts with the cachix post build steps which shows the error.

**Comment by zowoq** [comment]
Failed when I deployed it, I don't know why it works in the vm test.

```
builtins.AttributeError: 'ShellCommand' object has no attribute 'to_buildstep'
```

**Comment by MagicRB** [comment]
Because the vmtest doesn't actually execute anything

**Comment by MagicRB** [comment]
@zowoq try now, it hopefully will work. (sorry for the back and forth, I don't have Cachix setup and don't really want to do it on my private infra...)

**Comment by zowoq** [comment]
```
pydantic_core._pydantic_core.ValidationError: 6 validation errors for PostBuildStep
environment.CACHIX_SIGNING_KEY.str
  Input should be a valid string [type=string_type, input_value=Secret(None), input_type=Secret]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
environment.CACHIX_SIGNING_KEY.Interpolate
  Input should be a valid dictionary or instance of Interpolate [type=model_type, input_value=Secret(None), input_type=Secret]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type
environment.CACHIX_AUTH_TOKEN.str
  Input should be a valid string [type=string_type, input_value=Secret(/run/secrets/cachix-auth-token), input_type=Secret]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
environment.CACHIX_AUTH_TOKEN.Interpolate
  Input should be a valid dictionary or instance of Interpolate [type=model_type, input_value=Secret(/run/secrets/cachix-auth-token), input_type=Secret]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type
command.3.str
  Input should be a valid string [type=string_type, input_value=Interpolate('result-%(prop:attr)s'), input_type=Interpolate]
    For further information visit https://errors.pydantic.dev/2.7/v/string_type
command.3.Interpolate
  Input should be a valid dictionary or instance of Interpolate [type=model_type, input_value=Interpolate('result-%(prop:attr)s'), input_type=Interpolate]
    For further information visit https://errors.pydantic.dev/2.7/v/model_type

```

**Comment by MagicRB** [comment]
ffs, I gotta I will be back later today.

**Comment by MagicRB** [comment]
Might work now... If it doesn't I'm going to setup Cachix because this is ceasing to be funny (not that it was at any point...)

**Comment by zowoq** [comment]
```
 pydantic_core._pydantic_core.ValidationError: 4 validation errors for PostBuildStep
 environment.CACHIX_SIGNING_KEY.str
   Input should be a valid string [type=string_type, input_value=Secret(None), input_type=Secret]
     For further information visit https://errors.pydantic.dev/2.7/v/string_type
 environment.CACHIX_SIGNING_KEY.Interpolate
   Input should be a valid dictionary or instance of Interpolate [type=model_type, input_value=Secret(None), input_type=Secret]
     For further information visit https://errors.pydantic.dev/2.7/v/model_type
 environment.CACHIX_AUTH_TOKEN.str
   Input should be a valid string [type=string_type, input_value=Secret(/run/secrets/cachix-auth-token), input_type=Secret]
     For further information visit https://errors.pydantic.dev/2.7/v/string_type
 environment.CACHIX_AUTH_TOKEN.Interpolate
   Input should be a valid dictionary or instance of Interpolate [type=model_type, input_value=Secret(/run/secrets/cachix-auth-token), input_type=Secret]
     For further information visit https://errors.pydantic.dev/2.7/v/model_type
```

**Comment by MagicRB** [comment]
Okay im setting up cachix...

**Comment by MagicRB** [comment]
Or at least mocking it

**Comment by zowoq** [comment]
I've updated this after https://github.com/nix-community/buildbot-nix/pull/259, I think a minor cachix fix is still needed for the signing key, the cachix example is updated and I'd like to have the nixos test load the cachix post build step and confirm that the service doesn't crash.

**Pull request merged**
